### ISSUE TITLE
Incompatible Mod set

### ISSUE THREAD

**Issue by BrunoLiddell** [SolidBlock-cn/BRRP#1]
Hi!

There's seems to be an issue with the last version. I'm playing on Minecraft 1.19 and using the 0.7.0 version of the mod, and I get this error when I try launching the game (I'm using MultiMC in case that matters):

![brrp_error_v0 7 0](https://user-images.githubusercontent.com/57353858/176017469-a8fbcf7d-99d8-4f9d-ad31-87924239cb19.png)

I wanted to use this alongside the Extended Block Shapes mod (version 1.5.2). When I try using both of them, same error with an additional warning:

![brrp_error_v0 7 0_extshape](https://user-images.githubusercontent.com/57353858/176017908-4fb6dbc9-976d-4b0a-8147-75caedccd7f2.png)

**Comment by TalEdd** [comment]
You can edit the fabric.json within the mod using 7zip or winrar and notepad++ to change the breaks portion to a version that's non-existent and higher than 1.19. Its working for me this way.
![image](https://user-images.githubusercontent.com/63492921/177538860-dd290c64-72a7-4940-b67a-fa405e19719d.png)

**Comment by SolidBlock-cn** [comment]
Please download the correct mod for your Minecraft version.
