### ISSUE TITLE
1.0.3-beta.1-1.20.5 crashes outside of devenv

### ISSUE THREAD

**Issue by Fourmisain** [SolidBlock-cn/BRRP#11]
I was just porting a mod to 1.20.5 using BRRP 1.0.3-beta.1, and it appears to work perfectly inside the devenv.

Outside the devenv however I get various `NoSuchFieldError`, e.g. when calling `RuntimeResourcePack.create()` I get:
> Caused by: java.lang.NoSuchFieldError: Class net.minecraft.class_52 does not have member field 'com.mojang.serialization.Codec CODEC'
	at pers.solid.brrp.v1.api.RuntimeResourcePack.<clinit>(RuntimeResourcePack.java:98)
	at fourmisain.dirtnt.DirTnt.onInitialize(DirTnt.java:104)

(`class_52` = `LootTable`)

Similarly, when calling `IdentifiedTagBuilder.createBlock`:
> Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2960 net.minecraft.class_6862.id()'
	at pers.solid.brrp.v1.tag.IdentifiedTagBuilder.createBlock(IdentifiedTagBuilder.java:52)
	at fourmisain.dirtnt.DirTnt.onInitialize(DirTnt.java:105)

(`class_6862` = `TagKey`)

It looks like the method/field names aren't properly remapped, while the class names are, which is really weird.

**Comment by SolidBlock-cn** [comment]
Thanks for the report. I'll investigatae into it.

**Comment by Fourmisain** [comment]
Ah, I missed your release [again](https://github.com/SolidBlock-cn/BRRP/issues/10#issuecomment-1772944577)!

1.0.3 works perfectly, thanks!
