### ISSUE TITLE
compat with my fork

### ISSUE THREAD

**Issue by Trinsdar** [SolidBlock-cn/BRRP#2]
I recommend you make the forge version compatible with my fork of arrp(I ported it to forge): 
https://github.com/Reforged-Mods/ARRP-forge/tree/1.18.x-forge

**Comment by SolidBlock-cn** [comment]
Your fork seems to have a prblem: the `RRPInitEvent` seems to be only registered on client, and `ARRP.particleFactoryRegister` seems to take a parameter that exists only in client. Could you ensure your fork can launch correctly in dedicated server?

**Comment by SolidBlock-cn** [comment]
Finished.
