### ISSUE TITLE
BRRP与memoryleakfix冲突

### ISSUE THREAD

**Issue by RegulusSource** [SolidBlock-cn/BRRP#6]
只要BRRP和memoryleakfix同时加载就会报错导致游戏无法正常运行
报错文件:
[crash-2023-02-10_21.20.30.7515-quilt_loader.txt](https://github.com/SolidBlock-cn/BRRP/files/10708071/crash-2023-02-10_21.20.30.7515-quilt_loader.txt)
[crash-2023-02-10_21.38.33.2991-quilt_loader.txt](https://github.com/SolidBlock-cn/BRRP/files/10708072/crash-2023-02-10_21.38.33.2991-quilt_loader.txt)

**Comment by SolidBlock-cn** [comment]
我刚刚在Minecraft 1.19.3、Fabric Loader 0.14.17、BRRP 0.8.2和memory leak fix 0.7.0进行了测试，发现游戏能够正常启动。但是，在 #5 中有反馈称在 Fabric Loader 0.14.11 不兼容，而我在 Fabric Loader 0.14.17 中测试是正常的。
所以我推测这里可能是 Quilt Loader 的问题。
您能否提供 `	at net.devtech.arrp.BRRPDevelopment.<clinit>(BRRPDevelopment.java:58)` 之后的详细堆栈？

**Comment by SolidBlock-cn** [comment]
此问题可能与 #3 重复了，考虑到这个是 Quilt 所以暂时不关闭议题。

**Comment by SolidBlock-cn** [comment]
刚刚发布了最新版本0.9.0，请再次进行尝试。

**Comment by SolidBlock-cn** [comment]
如果仍遇到此问题，请重新打开本帖。
