### ISSUE TITLE
[HELP] Register my pack after another mod

### ISSUE THREAD

**Issue by Dreaming-Codes** [SolidBlock-cn/BRRP#8]
How can I register my pack after another mod to remove a recipe of another mod.

I've noticed that if I disable it with
/datapack disable "Runtime Resource Pack immersiveposres:runtime_resources"
and then I run
/datapack enable "Runtime Resource Pack immersiveposres:runtime_resources"
it works

**Comment by SolidBlock-cn** [comment]
The mod use Fabric API's events. You can call `addPhaseOrdering` of `net.fabricmc.fabric.api.event.Event`. But I've not tested it.
